name: Develop Branch
on:
  push:
    branches:
      - develop

jobs:
  run-tests:
    name: Tests
    uses: ./.github/workflows/test.yml
  run-coverage:
    name: Coverage
    uses: ./.github/workflows/coverage.yml
